sider/goodcheck

CHANGELOG.md
=> Fix version 1.1.0's CHANGELOG update date

lib/goodcheck/commands/init.rb, test/smoke_test.rb
This PR improves the `goodcheck init` command a bit.
- Add different cases of `glob`.
- Add a test case that `goodcheck test` verify a generated file by `goodcheck init`.
=> Improve a generated file by `goodcheck init`

.rubocop.yml
=> Setup rubocop

README.md
Published Docker images to [DockerHub](https://hub.docker.com/r/sider/goodcheck/).
=> Change Docker usage to one using DockerHub

README.md, goodcheck.gemspec, lib/goodcheck/analyzer.rb, lib/goodcheck/commands/test.rb, lib/goodcheck/config.rb, lib/goodcheck/config_loader.rb, lib/goodcheck/glob.rb, lib/goodcheck/pattern.rb, test/check_command_test.rb, test/config_loader_test.rb
```yml
rules:
- id: foo
pattern:
- literal: GitHub
glob: "**/*.html"
- literal: white
glob: "**/*.css"
```
=> Let each pattern have glob

Dockerfile, README.md, Rakefile
* Update `README.md`
* Fix `ENTRYPOINT` in Dockerfile
I plan to release a new version after merging this PR.
=> Prepare for docker image

CHANGELOG.md, Dockerfile
* Use `rubylang` Docker image as a base
* Fix goodcheck installation
=> Fix Dockerfile

docusaurus/website/yarn.lock
Via the following commands:
$ yarn audit
$ yarn upgrade
$ yarn audit
=> Fix vulnerabilities of npm packages

goodcheck.gemspec
https://guides.rubygems.org/specification-reference/#licenses=
=> Add `licenses` to gemspec

goodcheck.yml
https://github.com/sider/goodcheck-rules/blob/master/rules/typo.yml
=> Add goodcheck.yml for detecting typos

.travis.yml
Updated to each latest version 🆙
=> [Travis] Update Ruby versions

lib/goodcheck/cli.rb, test/smoke_test.rb
- Fix help text.
- Show help and exit with 1 when command is invalid.
=> Improve help

CHANGELOG.md, goodcheck.yml, lib/goodcheck/commands/check.rb, lib/goodcheck/glob.rb, test/check_command_test.rb
=> Check dot files (except for .git, .svn, .hg)

CHANGELOG.md, lib/goodcheck/commands/test.rb, test/test_command_test.rb
- Add a summary.
- Show a special message when no rules.
Fix #75
=> Improve `test` command output

lib/goodcheck/commands/test.rb
=> Make `test` command output a bit colorful

.github/workflows/test.yml
=> Try CI via GitHub Actions

.github/workflows/test.yml, Rakefile, benchmark/gc.c
For the test file for benchmark, [`gc.c`](https://github.com/ruby/ruby/blob/master/gc.c) in the Ruby source repository is used.
See also <https://ruby-doc.org/stdlib-2.7.0/libdoc/benchmark/rdoc/Benchmark.html>.
=> Add benchmark

README.md, lib/goodcheck/buffer.rb, lib/goodcheck/commands/check.rb, test/buffer_test.rb, test/check_command_test.rb
resolves: https://github.com/sider/goodcheck/issues/74
Ok, this has been a long time coming, but this project got reprioritized, so it took me a while to get back to it.
Just to be clear, this isn't a finished work. It doesn't yet address multiple languages, and I'd like to add a lot more tests at the buffer and check levels.
I'm hoping to get some early feedback on this approach since it goes in a different direction from what we discussed. Comments on style etc. are also very welcome since I'm not familiar with this project, and I don't have an established ruby coding style.
Thanks for reviewing!
Next Steps:
=> Add disable lines

CHANGELOG.md, goodcheck.gemspec, lib/goodcheck.rb, lib/goodcheck/import_loader.rb, test/import_loader_test.rb
=> Replace `httpclient` with `net/http`

docusaurus/website/yarn.lock
```console
$ rm yarn.lock && yarn install
```
=> Regenerate yarn.lock to fix security alerts

.github/workflows/test.yml, Rakefile, test/goodcheck_benchmark.rb
Fix #117
See also:
- https://github.com/seattlerb/minitest/blob/v5.14.2/lib/minitest/benchmark.rb
- https://chriskottom.com/blog/2015/04/minitest-benchmark-an-introduction/
=> Use Minitest::Benchmark

CHANGELOG.md, docusaurus/docs/configuration.md
=> Add missing doc for importing glob feature

test/pattern_command_test.rb
This change adds the unit test for the `goodcheck pattern` command.
=> Add missing test for `goodcheck pattern`

.rubocop.yml
Using the default configuration of Sider.
=> Run RuboCop on Sider

lib/goodcheck/commands/config_loading.rb
https://sider.review/gh/repos/112739662/branches/master/commits/6d85e8b1b613bd2bd7c7e622018b45efe93ed09c#issue-105158285
=> Fix `Lint/MissingSuper` issue

lib/goodcheck/commands/config_loading.rb
https://sider.review/gh/repos/112739662/branches/master/commits/4145e6a2ab0a27091fe70fadffdf4174adb6c917#issue-105158491
=> Fix `Security/YAMLLoad` issue

docusaurus/docs/rules.md
=> Add a rule example for offensive words

README.md
- Add a Docker example
- Add a link to the website
=> Improve "Getting started" in README

.github/workflows/test.yml
3.0 is the latest version of Ruby.
=> Use Ruby 3.0 by default on CI

CHANGELOG.md, lib/goodcheck/commands/config_loading.rb, lib/goodcheck/config_loader.rb, test/config_loader_test.rb, test/test_command_test.rb
=> Improve output error message on RegexpError

goodcheck.yml
https://github.com/sider/goodcheck-rules/releases/tag/v0.0.1
See #190
=> Test `.tar.gz` for importing with real repository

goodcheck.yml
=> Use `exclude_binary` option

goodcheck.yml
https://github.com/sider/goodcheck-rules/releases/tag/v0.0.3
=> Bump goodcheck-rules from 0.0.1 to 0.0.3

CHANGELOG.md, lib/goodcheck/reporters/text.rb, test/check_command_test.rb
=> Output `justification` with text format
