sider/goodcheck

- CHANGELOG.md
- lib/goodcheck/commands/check.rb
- test/check_command_test.rb
Stop checking the config file with `$ goodcheck check`. If you really want to check the config file, give the file to the commandline.
> Ignore config files from checking

- lib/goodcheck/commands/check.rb
- test/check_command_test.rb
- test/test_case_builder.rb
When goodcheck analyzes a broken symlink, it raises the following error:
```
$ goodcheck check --format json
Starting analysis...
No such file or directory @ realpath_rec - /tmp/symtest/test.yml
$ ls -l
total 4
-rw-r--r-- 1 wata727 251 Feb 21 15:03 goodcheck.yml
lrwxrwxrwx 1 wata727   8 Feb 21 15:04 link.yml -> test.yml
```
In order to avoid this error, it should stop resolving realpath.
> Stop resolving realpath for broken symlinks

- Dockerfile
- README.md
- Rakefile
Add Docker support. By this pull-request, user can use goodcheck with `docker build` and `docker run` if user does not install Ruby 2.4 in the host machine.
I think we can close #7 with this pull-request. What do you think? @soutaro @sumyapp
> Docker support🐳

- lib/goodcheck/reporters/json.rb
- test/json_reporter_test.rb
This commit makes the JSON reporter #analysis method return the JSON
of the issues in addition to printing the JSON to stdout. This is to
enable using the reporter programmatically through other tools.
> Return analysis JSON from JSON reporter

- lib/goodcheck/config_loader.rb
- test/config_loader_test.rb
A rule with N literal patters would
process each file N times for that rule.
Insted, split the literal patterns in two groups:
* case sensitive
* case insensitive
For each group combine the patterns into a regexp matching them.
> Speed-up processing of N literal patterns

- lib/goodcheck/cli.rb
More user-friendly description.
```
$ goodcheck check -h
Usage: goodcheck check [options] dirs...
-c, --config=CONFIG
-R, --rule=RULE
--format=FORMAT
```
```
$ bundle exec ./exe/goodcheck check -h
Usage: goodcheck check [options] dirs...
-c, --config=CONFIG
-R, --rule=RULE
--format=<text|json> [default: 'text']
```
> Improve CLI help for `--formatter` option of `check` command

- lib/goodcheck/commands/check.rb
Skip dotfiles unless the user explicitly provides
them by command line (Fix Issue#20).
> Do not load dotfiles by default if glob is nil

- CHANGELOG.md
- README.md
- lib/goodcheck/commands/check.rb
- test/check_command_test.rb
- test/smoke_test.rb
As discussed in https://github.com/sider/goodcheck/issues/24, `goodcheck check` now exits with `2` when it finds some matching text.
The error status is `2` and not `1` because `1` is what `ruby` exits from an error.
> Exit with 2 when it finds matching text

- goodcheck.gemspec
Currently, the latest version is 0.7.1, there is no reason to continue to depend on the old version.
In our environment, we can not resolve the following conflict and update the goodcheck.
```
Bundler could not find compatible versions for gem "strong_json":                                                         
In snapshot (Gemfile.lock):                                                                                             
strong_json (= 0.5.0)                                                                                                 
In Gemfile:                                                                                                             
goodcheck was resolved to 1.4.0, which depends on …
```
> Bump StrongJSON version

- .gitignore
- lib/goodcheck/reporters/text.rb
- test/check_command_test.rb
This PR fixes `TypeError` raised when checking rules matching End-of-Line (EOL).
For example:
```yaml
rules:
- id: foo
message: Foo
pattern:
regexp: "foo.*"
```
Checked file (`foo.txt`):
```
foo\r\n
```
Run `goodcheck check foo.txt` command.
Error:
```
TypeError: no implicit conversion of nil into String
/Users/koba/git/ybiquitous/goodcheck/lib/goodcheck/reporters/text.rb:29:in `+'
/Users/koba/git/ybiquitous/goodcheck/lib/goodcheck/reporters/text.rb:29:in `issue'
/Users/koba/git/ybiquitous/goodcheck/lib/goodcheck/commands/check.rb:35:in `block (4 levels) in run'
/Users/koba/git/ybiquitous/goodcheck/lib/goodcheck/analyzer.rb:40:in `each'
/Users/koba/git/ybiquitous/goodcheck/lib/goodcheck/analyzer.rb:40:in `scan'
/Users/koba/git/ybiquitous/goodcheck/lib/goodcheck/commands/check.rb:33:in …
```
> Fix error when pattern including End-of-Line

- lib/goodcheck/buffer.rb
- test/buffer_test.rb
- test/check_command_test.rb
- test/json_reporter_test.rb
Fix JSON reporter position calculation failure, which didn't handle correctly when the string ends with `\n`. (The line and column containd `nil`.)
> Fix position calculation

- README.md
- lib/goodcheck/commands/check.rb
- lib/goodcheck/commands/init.rb
- lib/goodcheck/config.rb
- lib/goodcheck/config_loader.rb
- test/check_command_test.rb
- test/config_loader_test.rb
- test/config_test.rb
This PR allows writing `exclude:` attribute in the config file.
```yaml
rules: []
exclude:
- node_modules
- vendor
```
The value of `exclude` is a glob pattern. I'm not very sure if glob pattern is the best option for this. (`.gitignore` syntax may be another possible option.)
> Add exclude attribute in configuration

- lib/goodcheck/analyzer.rb
- lib/goodcheck/config_loader.rb
- lib/goodcheck/issue.rb
- lib/goodcheck/reporters/json.rb
- lib/goodcheck/reporters/text.rb
- lib/goodcheck/rule.rb
- sample.yml
- test/analyzer_test.rb
- test/check_command_test.rb
- test/config_loader_test.rb
- test/json_reporter_test.rb
Now we can write a *negated* rule to check the absence of patterns in a file.
```yaml
rules:
- id: foo
not:
pattern: frozen_string_literal: true
message: |
Specify frozen_string_literal magic comment.
glob:
- "**/*.rb"
```
> Test there is no content

- lib/goodcheck/analyzer.rb
- lib/goodcheck/config_loader.rb
- test/analyzer_test.rb
- test/check_command_test.rb
- test/config_loader_test.rb
We can now define a rule without `pattern`.
This rule matches any file specified in `glob` (`glob` is required in this case.) This rule is useful to detect if a file is changed or not, would be useful for reviewing `Gemfile.lock`, `package-lock.json`, `db/schema.rb`, ...
```yaml
rules:
- id: migration
message: |
See the operation manual for migration: https://example.com/docs/1
glob: "db/schema.rb"
```
> Add rule without pattern

- goodcheck.gemspec
- lib/goodcheck/analyzer.rb
- lib/goodcheck/config_loader.rb
- lib/goodcheck/pattern.rb
- test/analyzer_test.rb
- test/check_command_test.rb
- test/config_loader_test.rb
- test/pattern_test.rb
- test/test_helper.rb
Add a feature to capture a substring in a token pattern. This allows writing easily a really frequent pattern; *You shouldn't use other than the following*.
```yaml
rules:
- id: bgcolor
message: |
You shouldn't use colors other than ones defined in our global color palette
pattern:
- token: bgcolor=${color:string}
where:
color:
not:
- primary.main
- secondary.main
- error.main
- text.primary
```
The `${<name>:<type>}` is compiled to a regexp, and the part will be captured and tested during analysis.
> Add variable syntax in token pattern

- lib/goodcheck/pattern.rb
- test/config_loader_test.rb
- test/pattern_test.rb
It generates a shortest-match-regexp. This works well if you specify the start and end characters.
```
token: background: url(${url});
where:
size: true
```
If the predecessor and successor are open and close parens, it supports nesting up to five-levels.
```
token: backgroundColor={${color}}
where:
color: true
```
The `${color}` can be something like `{ r: r(), g: g(), b: b(), a() }`, it has 1-level nesting of `{` and `}`.
> Fix variable pattern without type

- .travis.yml
- Rakefile
This adds two Rake tasks below:
- `docs:build`
- `docs:install_deps`
These tasks requires that Yarn is installed.
> Run docs generation on Travis CI

- lib/goodcheck/reporters/text.rb
- test/check_command_test.rb
> Fix `check` error on empty files

- README.md
- Rakefile
- Add `rake docs:publish`.
- Update the releasing instructions in README.
> Improve publishing documentation

- goodcheck.gemspec
- lib/goodcheck/buffer.rb
- lib/goodcheck/commands/config_loading.rb
- lib/goodcheck/config_loader.rb
- lib/goodcheck/issue.rb
- lib/goodcheck/trigger.rb
- test/check_command_test.rb
- test/config_loader_test.rb
- test/init_command_test.rb
- test/pattern_test.rb
- test/smoke_test.rb
You can see the warnings via `bundle exec rake` command.
- `Passing filename with the 2nd argument of Psych.load is deprecated. Use keyword argument like Psych.load(yaml, filename: ...) instead.`
- `warning: instance variable @location not initialized`
See the Travis [build log](https://travis-ci.org/sider/goodcheck/jobs/609092842#L269) for details.
> Fix Ruby warnings

- .github/workflows/test.yml
- Rakefile
Usage:
```shell
rake benchmark:run # default: n=1000
```
Or,
```shell
rake benchmark:run[10000]
```
> Add `n` option to `benchmark:run` task

- .github/workflows/release.yml
Using <https://github.com/softprops/action-gh-release>.
> Automate releasing via GitHub Actions

- .github/workflows/test.yml
- Use [ruby/setup-ruby](https://github.com/ruby/setup-ruby) instead of [eregon/use-ruby-action](https://github.com/eregon/use-ruby-action)
- Use `bundle config set` instead of `bundle install --path` option.
See <https://github.com/rubygems/bundler/blob/master/UPGRADING.md#cli-deprecations>
> Update CI configurations

- .github/workflows/test.yml
`ruby/setup-ruby` runs the `gem install bundler` and `bundle config` commands,
so this change removes these needless commands.
- https://github.com/ruby/setup-ruby/blob/8bc9ca9ace0139aae24423f15269b9673354b495/index.js#L234
- https://github.com/ruby/setup-ruby/blob/8bc9ca9ace0139aae24423f15269b9673354b495/index.js#L250
> Simplify test workflows on Actions

- test/analyzer_test.rb
- test/buffer_test.rb
- test/check_command_test.rb
- test/config_loader_test.rb
- test/config_test.rb
- test/import_loader_test.rb
- test/init_command_test.rb
- test/json_reporter_test.rb
- test/pattern_test.rb
- test/smoke_test.rb
- test/test_command_test.rb
- test/test_helper.rb
- Simplify `require "test_helper"`
- Remove needless `$LOADPATH` setting
> Refactor tests

- CHANGELOG.md
- lib/goodcheck.rb
- lib/goodcheck/cli.rb
- lib/goodcheck/commands/check.rb
- lib/goodcheck/commands/init.rb
- lib/goodcheck/commands/pattern.rb
- lib/goodcheck/commands/test.rb
- lib/goodcheck/exit_status.rb
- test/smoke_test.rb
- Add option messages for each sub-command.
- Reduce duplicate or needless code.
For example:
```console
$ goodcheck check -h
Usage: goodcheck check [options] paths...
-c, --config=CONFIG              Configuration file path [default: 'goodcheck.yml']
-v, --verbose                    Set log level to verbose
-d, --debug                      Set log level to debug
--force                      Download importing files always
-R, --rule=RULE                  Only rule(s) to check
--format=<text|json>         Output format [default: 'text']
--version                    Print version
-h, --help                       Show help and quit
```
> Improve CLI help and error messages

- CHANGELOG.md
- lib/goodcheck/commands/check.rb
- test/check_command_test.rb
> Fail if missing rules on `goodcheck check` command

- CHANGELOG.md
- goodcheck.gemspec
This change aims to:
- reduce this gem size
- make diffend.io view more useful (see <https://my.diffend.io/gems/goodcheck/2.5.1/2.5.2>)
---
```console
$ du -hs goodcheck-2.5.2.gem*
28K	goodcheck-2.5.2.gem
820K	goodcheck-2.5.2.gem.before
```
---
Run: `gem build && gem unpack goodcheck-2.5.2.gem && tree goodcheck-2.5.2`
```
goodcheck-2.5.2
├── CHANGELOG.md
├── Dockerfile
├── Gemfile
├── LICENSE
├── README.md
├── Rakefile
├── bin
│   ├── console
│   └── setup
├── cheatsheet.pdf
├── docusaurus
│   ├── Dockerfile
│   ├── docker-compose.yml
│   ├── docs
│   │   ├── commands.md
│   │   ├── configuration.md
│   │   ├── development.md
│   │   ├── getstarted.md
│   │   └── rules.md
│   └── website
│       ├── README.md
│       ├── core
│       │   └── Footer.js
│       ├── package.json
│       ├── …
```
> Reduce needless files in this gem

- goodcheck.yml
- lib/goodcheck.rb
- lib/goodcheck/config_loader.rb
- lib/goodcheck/error.rb
- lib/goodcheck/import_loader.rb
This change allows to rescue all errors in Goodcheck as follows:
```ruby
begin
rescue Goodcheck::Error => error
end
```
> Add `Goodcheck::Error` as a base error class

- CHANGELOG.md
- lib/goodcheck/commands/config_loading.rb
- test/check_command_test.rb
- test/test_command_test.rb
For example:
```console
$ goodcheck test --config foo.yml
Configuration file not found: foo.yml
$ goodcheck check --config foo.yml
Configuration file not found: foo.yml
```
Fix #121
> Improve error message when config file is not found

- .github/workflows/release.yml
- .github/workflows/test.yml
- Release: use a tag instead of a commit sha.
- Test: set `bundler-cache: true`
> Improve workflows on Actions

- CHANGELOG.md
- docusaurus/docs/configuration.md
- lib/goodcheck/config_loader.rb
- lib/goodcheck/glob.rb
- test/analyzer_test.rb
- test/check_command_test.rb
- test/config_loader_test.rb
- test/smoke_test.rb
For example:
```yaml
rules:
- id: example1
pattern: foo
message: Disallow "foo"
glob:
- { pattern: "**/*.html", exclude: "**/test/**" }
- { pattern: "**/*.txt", exclude: ["**/test/**", "**/spec/**"] }
```
Fix #119
> Add `rules[].glob.exclude` option to `goodcheck.yml`

- lib/goodcheck.rb
`Set` is used in `Goodcheck::CLI` class:
https://github.com/sider/goodcheck/blob/b23ad97feb9c31898282a1a7394975dc82b27c09/lib/goodcheck/cli.rb#L174
> Add missing `require "set"`

- lib/goodcheck/import_loader.rb
- test/import_loader_test.rb
This change allows you to write *glob* patterns for `import:` in `goodcheck.yml`.
For example:
```yaml
import:
- "rules/**/*.yml"
- "goodcheck-*.yml"
```
I believe this feature so useful if you want to manage many rules in some files.
Close #133
> Glob support for importing rules

- Rakefile
For the development of the documentation.
Usage:
```console
$ bundle exec rake docs:start
yarn install
yarn install v1.22.10
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.40s.
!!!
!!! Open the URL in your browser: http://127.0.0.1:3000/goodcheck/docs/next/getstarted
!!!
yarn run start
yarn run v1.22.10
warning package.json: No license field
$ docusaurus-start
LiveReload server started on port 35729
Docusaurus server started on port 3000
```
> Add rake task `docs:start`

- goodcheck.gemspec
`~>` is not intuitive. Instead, this uses `>=` and `<`.
The actual dependencies are unchanged.
> Refactor dependency constraints not to use `~>`

- .github/workflows/test.yml
- goodcheck.gemspec
- goodcheck.yml
- test/test_helper.rb
Use the `simplecov` gem:
https://github.com/simplecov-ruby/simplecov
Also, the coverage report will be saved and available on GitHub Actions.
> Enable test coverage

- CHANGELOG.md
- lib/goodcheck/commands/check.rb
- lib/goodcheck/reporters/json.rb
- lib/goodcheck/reporters/text.rb
- test/check_command_test.rb
- test/smoke_test.rb
This change aims to make the `--format=text` output more useful and helpful.
- Add summary about files and issues
- Change the output format like the [Clang style](https://clang.llvm.org/diagnostics.html).
For example:
```console
$ exe/goodcheck check README.md
README.md:7:29: Did you mean "GitHub"?
What if a misspelling like `Github` for `GitHub` can be found automatically?
^~~~~~
1 file inspected, 1 issue detected
```
> Improve text reporter

- lib/goodcheck/config_loader.rb
- test/init_command_test.rb
Follow-up of PR #164
See also:
- https://ruby-doc.org/stdlib/libdoc/yaml/rdoc/YAML.html#module-YAML-label-Security
- https://ruby-doc.org/stdlib/libdoc/psych/rdoc/Psych.html#safe_load-method
- https://ruby-doc.org/stdlib/libdoc/psych/rdoc/Psych.html#load-method
- https://sider.review/gh/repos/112739662/branches/master/commits/6a19c5be34a1ecf651b7c15b5460691a5e7dee62?tools%5B%5D=rubocop&rules%5B%5D=Security%2FYAMLLoad
> Use `YAML.safe_load` instead of `YAML.load`

- .github/workflows/test.yml
- CHANGELOG.md
- goodcheck.gemspec
Ruby 2.4 has reached EOL already on April 2020.
See <https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/>
> Drop support of Ruby 2.4

- CHANGELOG.md
- docusaurus/docs/commands.md
- lib/goodcheck/commands/check.rb
- lib/goodcheck/commands/config_loading.rb
- lib/goodcheck/commands/test.rb
- lib/goodcheck/exit_status.rb
- test/test_command_test.rb
I think it better to add a new status to ensure the consistency through all the sub commands.
Close #116
NOTE: This is a potentially breaking change. Previously, the `goodcheck test` command exited with `1`, not `3`.
> `goodcheck test` exit with `3` on tests failed

- .github/workflows/test.yml
- goodcheck.gemspec
- test/test_helper.rb
- Remove the `minitest-reporters` gem, which seems redundant.
- Enable the coverage conditionally, not always.
> Refactor testing

- sider.yml
- Use the edge version of Goodcheck.
- Use the default version of RuboCop.
- Remove the branch settings.
> Refactor sider.yml

- CHANGELOG.md
- lib/goodcheck/import_loader.rb
- test/import_loader_test.rb
For example:
```yaml
import:
- "lib/**/*.{yml,yaml}"
```
```console
$ exe/goodcheck test
#<URI::InvalidURIError: bad URI(is not URI?): "lib/**/*.{yml,yaml}">
...
```
> Fix importing error with extended glob

- .github/workflows/test.yml
- docusaurus/docs/configuration.md
- goodcheck.gemspec
- goodcheck.yml
- lib/goodcheck/commands/check.rb
- lib/goodcheck/config.rb
- lib/goodcheck/config_loader.rb
- test/check_command_test.rb
- test/config_test.rb
This change introduces a new option for `goodcheck.yml`: `exclude_binary`.
Usage:
```yaml
exclude_binary: true    # default: false
```
This change uses the `marcel` gem to detect if a file is binary or not.
See <https://github.com/rails/marcel>
> Introduce `exclude_binary` option

- CHANGELOG.md
- lib/goodcheck/import_loader.rb
- test/import_loader_test.rb
This change aims to prevent the following error:
```
#<RuntimeError: Error: HTTP GET #<URI::HTTPS https://github.com/sider/goodcheck-rules/archive/refs/tags/v0.0.1.tar.gz> #<Net::HTTPTooManyRequests 429 Too Many Requests readbody=true>>
```
> Retry HTTP GET request on importing rules

- CHANGELOG.md
- lib/goodcheck/import_loader.rb
```
#<Net::OpenTimeout: execution expired>
/usr/local/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
/usr/local/lib/ruby/2.7.0/net/http.rb:960:in `open'
/usr/local/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
/usr/local/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/usr/local/lib/ruby/2.7.0/net/http.rb:958:in `connect'
/usr/local/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
/usr/local/lib/ruby/2.7.0/net/http.rb:932:in `start'
/usr/local/lib/ruby/2.7.0/net/http.rb:606:in `start'
/usr/local/lib/ruby/2.7.0/net/http.rb:481:in `get_response'
/home/analyzer_runner/ruby/gems/goodcheck-3.0.1/lib/goodcheck/import_loader.rb:141:in `http_get'
/home/analyzer_runner/ruby/gems/goodcheck-3.0.1/lib/goodcheck/import_loader.rb:114:in `load_http'
```
Related to #197
> Retry importing on Net::OpenTimeout

- CHANGELOG.md
- lib/goodcheck/import_loader.rb
- test/import_loader_test.rb
This change aims to fix the following error:
```
NoMethodError: undefined method `error_response?' for #<Net::OpenTimeout: execution expired>
```
> Fix HTTP GET retrying

- CHANGELOG.md
- goodcheck.yml
- lib/goodcheck/reporters/text.rb
- test/check_command_test.rb
- Use `dimgray` for a location and rule to clarify a path and message.
- Output a rule and severity for messages without a pattern.
For example:
> Improve coloring for text format
